-- 코드를 입력하세요
SELECT AUTHOR_ID,AUTHOR_NAME,CATEGORY, SUM(TOTAL) AS TOTAL_SALES
FROM
(SELECT B.BOOK_ID,B.AUTHOR_ID,(PRICE*SALES) AS TOTAL ,AUTHOR_NAME, CATEGORY
FROM BOOK_SALES AS S,AUTHOR AS A, BOOK AS B
WHERE SALES_DATE REGEXP "2022-01" AND B.AUTHOR_ID=A.AUTHOR_ID AND S.BOOK_ID=B.BOOK_ID) AS C
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC