-- 코드를 입력하세요
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS ,ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS I, REST_REVIEW AS R
WHERE I.REST_ID=R.REST_ID
AND
ADDRESS LIKE "서울%"
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC
# SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) SCORE
# FROM REST_REVIEW R
#     JOIN REST_INFO I
#     ON R.REST_ID = I.REST_ID
# WHERE I.ADDRESS LIKE "서울%"
# GROUP BY R.REST_ID
# ORDER BY 6 DESC, 4 DESC