-- 코드를 입력하세요
SELECT FLAVOR
FROM
((SELECT FLAVOR,SUM(TOTAL_ORDER) AS TOTAL FROM FIRST_HALF GROUP BY FLAVOR)
UNION ALL
(SELECT FLAVOR,SUM(TOTAL_ORDER) AS TOTAL FROM JULY GROUP BY FLAVOR)) AS A
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC
Limit 3