-- 코드를 입력하세요 
SELECT USER_ID, NICKNAME ,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B, USED_GOODS_USER AS U
WHERE USER_ID=WRITER_ID AND STATUS="DONE"
GROUP BY WRITER_ID
HAVING SUM(PRICE)>=700000
ORDER BY TOTAL_SALES