-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT,LEFT(REVIEW_DATE,10)
FROM REST_REVIEW AS R, MEMBER_PROFILE AS M
WHERE R.MEMBER_ID=M.MEMBER_ID AND
R.MEMBER_ID IN
(SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) IN 
(SELECT MAX(C)
FROM
(SELECT MEMBER_ID, COUNT(MEMBER_ID) AS C
FROM REST_REVIEW
GROUP BY MEMBER_ID) AS COU))
ORDER BY REVIEW_DATE,REVIEW_TEXT