-- 코드를 입력하세요
SELECT
CONCAT("/home/grep/src/",A.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM
(SELECT * FROM USED_GOODS_BOARD AS B ORDER BY VIEWS DESC LIMIT 1)
AS A, USED_GOODS_FILE AS F
WHERE F.BOARD_ID=A.BOARD_ID
ORDER BY FILE_ID DESC